login,signup pages
Hemasree5c2/BorrowMyProducts pull request #8
Opened 2020-04-22 08:11 UTC by Hemasree5c2

2020-04-22 08:14 UTC, ghost requested changes

2020-04-22 08:14 UTC, MohammedAtif commented on BorrowMyProducts/src/main/java/com/techhunters/borrowmyproducts/controller/AuthController.java
> +        if(!pattern.matcher(user.getEmail()).matches()) {
Check how to validate the request object correctly in spring

2020-04-23 13:58 UTC, srivathsa-002 commented on BorrowMyProducts/pom.xml
> +<!--		<dependency>-->
You can use spring security dependency by excluding SecurityAutoConfiguration.class in the main application

2020-04-23 14:02 UTC, Hemasree5c2 commented on BorrowMyProducts/pom.xml
> +<!--		<dependency>-->
okk..i will change it

2020-04-23 14:31 UTC, vangaru-shanmukha approved these changes

2020-04-23 14:32 UTC, bshashank81 reviewed
The code is fine, but all the logic of css and js are included along with the html. If the js, css and html are separated in different files, it increases the user readability.

2020-04-23 15:06 UTC, NeerajaGoli approved these changes

2020-04-24 00:52 UTC, merged